// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU2n6oooIezrBl4aaqtRebRe981CDjOOU',
    appId: '1:183650277171:web:2e4fa17e8894ee3a685046',
    messagingSenderId: '183650277171',
    projectId: 'flashchat-ios-9e6d5',
    authDomain: 'flashchat-ios-9e6d5.firebaseapp.com',
    storageBucket: 'flashchat-ios-9e6d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5fLXZ3UHUWie8LyCpsnR1EJVcJ1Mma1g',
    appId: '1:183650277171:android:b434c46c4eba35e1685046',
    messagingSenderId: '183650277171',
    projectId: 'flashchat-ios-9e6d5',
    storageBucket: 'flashchat-ios-9e6d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByX4upusgh0jmEq1eb32HX4PtGstC_n9w',
    appId: '1:183650277171:ios:2d09ec3b61f7ca69685046',
    messagingSenderId: '183650277171',
    projectId: 'flashchat-ios-9e6d5',
    storageBucket: 'flashchat-ios-9e6d5.appspot.com',
    iosClientId: '183650277171-4l0ram4fhirm6kft9kid7qes51s509h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByX4upusgh0jmEq1eb32HX4PtGstC_n9w',
    appId: '1:183650277171:ios:2d09ec3b61f7ca69685046',
    messagingSenderId: '183650277171',
    projectId: 'flashchat-ios-9e6d5',
    storageBucket: 'flashchat-ios-9e6d5.appspot.com',
    iosClientId: '183650277171-4l0ram4fhirm6kft9kid7qes51s509h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
